from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('login/', auth_views.LoginView.as_view(template_name='login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('register/', views.register, name='register'),
    path('profile/', views.profile, name='profile'),
    path('exams/', views.exams, name='exams'),
    path('quiz/', views.quiz, name='quiz'),
    path('pay/', views.pay, name='pay'),
    path('scholarships/', views.scholarships, name='scholarships'),
    path('jobs/', views.jobs, name='jobs'),
    path('job-exams/', views.job_exams, name='job_exams'),
    path('job-ethiopian-airlines/', views.job_ethiopian_airlines, name='job_ethiopian_airlines'),
    path('job-ethio-telecom/', views.job_ethio_telecom, name='job_ethio_telecom'),
    path('job-insa/', views.job_insa, name='job_insa'),
    path('grade12-exams/', views.grade12_exams, name='grade12_exams'),
    path('grade12-natural/', views.grade12_natural, name='grade12_natural'),
    path('grade12-social/', views.grade12_social, name='grade12_social'),
    path('physics-exams/', views.physics_exams, name='physics_exams'),
    path('chemistry-exams/', views.chemistry_exams, name='chemistry_exams'),
    path('biology-exams/', views.biology_exams, name='biology_exams'),
    path('math-exams/', views.math_exams, name='math_exams'),
    path('civics-exams/', views.civics_exams, name='civics_exams'),
    path('history-exams/', views.history_exams, name='history_exams'),
    path('geography-exams/', views.geography_exams, name='geography_exams'),
    path('economics-exams/', views.economics_exams, name='economics_exams'),
    path('ict-exams/', views.ict_exams, name='ict_exams'),
    path('logic-exams/', views.logic_exams, name='logic_exams'),
    path('university-exams/', views.university_exams, name='university_exams'),
    path('astu-courses/', views.astu_courses, name='astu_courses'),
    path('astu-appliedmath1/', views.astu_appliedmath1, name='astu_appliedmath1'),

    path('aastu_courses/', views.aastu_courses, name='aastu_courses'),
    path('aau_courses/', views.aau_courses, name='aau_courses'),
    path('astu_appliedmath1_final/', views.astu_appliedmath1_final, name='astu_appliedmath1_final'),
    path('astu_appliedmath1_mid/', views.astu_appliedmath1_mid, name='astu_appliedmath1_mid'),
    path('astu_appliedmath1_outline/', views.astu_appliedmath1_outline, name='astu_appliedmath1_outline'),
    path('astu_appliedmath1_resources/', views.astu_appliedmath1_resources, name='astu_appliedmath1_resources'),
    path('astu_chemistry/', views.astu_chemistry, name='astu_chemistry'),
    path('astu_electrical/', views.astu_electrical, name='astu_electrical'),
    path('astu_physics1/', views.astu_physics1, name='astu_physics1'),
    path('astu_programming/', views.astu_programming, name='astu_programming'),
    path('ethio_network_engineer_exams/', views.ethio_network_engineer_exams, name='ethio_network_engineer_exams'),
    path('physics_2024/', views.physics_2024, name='physics_2024'),
    path('job_civil_service/', views.job_civil_service, name='job_civil_service'),
]
